### ISSUE TITLE
error con modulos

### ISSUE THREAD

**Issue by cinzunzas** [mariofix/django-payments-chile#14]
Hola @mariofix, estoy probando el package que has construido para poder operacionalizar medios de pago de CL. Pero me esta arrojando un error cuando intento llevar al cliente al medio de pago:

```
2024-11-21 13:14:11 Traceback (most recent call last):
2024-11-21 13:14:11   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-11-21 13:14:11     response = get_response(request)
2024-11-21 13:14:11   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-11-21 13:14:11     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-11-21 13:14:11   File "/usr/src/app/pagos/views.py", line 26, in payment_details
2024-11-21 13:14:11     form = payment.get_form(data=request.POST or None)
2024-11-21 13:14:11   File "/usr/local/lib/python3.10/site-packages/payments/models.py", line 146, in get_form
2024-11-21 13:14:11     provider = provider_factory(self.variant, self)
2024-11-21 13:14:11   File "/usr/local/lib/python3.10/site-packages/payments/core.py", line 169, in _default_provider_factory
2024-11-21 13:14:11     class_ = import_string(handler)
2024-11-21 13:14:11   File "/usr/local/lib/python3.10/site-packages/django/utils/module_loading.py", line 32, in import_string
2024-11-21 13:14:11     raise ImportError(
2024-11-21 13:14:11 ImportError: Module "django_payments_chile" does not define a "FlowProvider" attribute/class
``` 

btw, con otro medio de pago como "mercadopago" de django-payments, el flujo se ejecuta sin problemas. 

Se te ocurre que podría estar haciendo mal?

**Comment by mariofix** [comment]
Gracias! 
Creo que le falta un poco para poder ser usado en un proyecto, podrías intentar con mariofix/django-payments-flow?

Mi plan era hacer un módulo para cada integrador, pero después decidí mezclarlos en este paquete.

Este es el que va a seguir en el futuro, pero mariofix/django-payments-flow debería funcionar inmediatamente hoy.

Avísame porfavor.

-M

**Comment by cinzunzas** [comment]
Gracias por contestar rapido Mario!

Mira tuve que hacer downgrade de algunos packages, pero el error es el mismo:


```
2024-11-21 15:53:11 Traceback (most recent call last):
2024-11-21 15:53:11   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-11-21 15:53:11     response = get_response(request)
2024-11-21 15:53:11   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-11-21 15:53:11     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-11-21 15:53:11   File "/usr/src/app/pagos/views.py", line 26, in payment_details
2024-11-21 15:53:11     form = payment.get_form(data=request.POST or None)
2024-11-21 15:53:11   File "/usr/local/lib/python3.10/site-packages/payments/models.py", line 142, in get_form
2024-11-21 15:53:11     provider = provider_factory(self.variant, self)
2024-11-21 15:53:11   File "/usr/local/lib/python3.10/site-packages/payments/core.py", line 159, in _default_provider_factory
2024-11-21 15:53:11     class_ = getattr(module, class_name)
2024-11-21 15:53:11 AttributeError: module 'django_payments_flow' has no attribute 'FlowProvider'
``` 

y por ahí me parece que la version django-payments-flow==2024.9.23 no es compatible con pyflowcl==2024.9.28

```
24.68 The conflict is caused by:
24.68     The user requested pyflowcl==2024.9.28
24.68     django-payments-flow 2024.9.23 depends on pyflowcl<2.0 and >=1.2
``` 

cuando soluciona lo de las versiones quede en:

```
django-payments-flow==0.1.2
django-payments==2.0.0
pyflowcl==2024.9.28
```

con el error de arriba

**Comment by mariofix** [comment]
ultima version publicada: 2024.12.5
